# Generated by Django 4.2.7 on 2023-11-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Female'), (2, 'Male')], default=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Female'), (2, 'Male')], default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'doctor'), (2, 'patient'), (4, 'Receptionist')], default=2),
        ),
    ]
